{% set name = "intel-gpu-ocl-icd-system" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: generic
  number: 0
  skip: True  # [not linux]

requirements:
  run:
    - intel-opencl-rt

test:
  commands:
    - export ICD_FN=${CONDA_PREFIX}/etc/OpenCL/vendors/intel-ocl-gpu.icd
    - test -h ${ICD_FN}

about:
  home: https://github.com/IntelPython/{{ name|lower }}-feedstock
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Symlink system-wide OpenCL ICD file for Intel(R) GPUs to current environment'

  description: |
    Since GPU drivers are installed system-wide, and the OpenCL loader in conda environment
    is configured to look for ICD files in ``${CONDA_PREFIX}/etc/OpenCL/vendors`` to isolate
    the conda environment from the system environment, enabling discovery of Intel GPU devices
    by the OpenCL loader requires creation of appropriate ICD file in the conda environment's
    own vendors folder. This metapackage creates such an ICD as a symbolic link to the ICD
    installed system-wide.

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
    - ZzEeKkAa
